[package]
name = "runvy_app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
runvy_core = { path = "../runvy_core" }
runvy_ecs = { path = "../runvy_ecs" }
runvy_render = { path = "../runvy_render" }
runvy_render_api = { path = "../runvy_render_api" }
runvy_asset = { path = "../runvy_asset" }
runvy_script_api = { path = "../runvy_script_api" }

winit.workspace = true
