[workspace]
members = [
    # Crates:
    "crates/runvy_macros",
    "crates/runvy_engine",
    "crates/runvy_app",
    "crates/runvy_core",
    "crates/runvy_ecs",
    "crates/runvy_render",
    "crates/runvy_asset",
    # "crates/runvy_project",
    # "crates/runvy_editor",
    "crates/runvy_render_api",
    "crates/runvy_script_api",
    # Examples:
    "examples/audio_test",
    "examples/command_queue_test",
    "examples/console_test",
    "examples/lua_scripting_test",
    "examples/sandbox",
    "examples/sandbox_3d",
    "examples/scenemanager_test",
    "examples/ui_test",
    "examples/tilemap_test",
    "examples/timer_test",
]
exclude = ["templates"]
resolver = "2"

[workspace.package]
version = "0.8.0-pre.4"
authors = ["Nik Neza <nik.n.neza@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/runvyengine/runvy"
description = "2D/3D game engine in Rust"

[workspace.dependencies]
winit = { version = "0.30.13" }
pollster = { version = "0.4" }
wgpu = { version = "29.0" }
glam = { version = "0.32.1" }
gltf = { version = "1.4", features = ["import"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
