[package]
name = "runvy_render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
runvy_asset = { path = "../runvy_asset" }
runvy_render_api = { path = "../runvy_render_api" }
rusttype = "0.9"

winit.workspace = true
pollster.workspace = true
wgpu.workspace = true
glam.workspace = true
bytemuck = { version = "1.25.0", features = ["derive"] }
