use std::fs;
use std::path::{Path, PathBuf};

use crate::project::{
    ProjectAppConfig, ProjectBuildConfig, ProjectError, ProjectManifest, ProjectPaths,
};
use crate::world_asset::{create_empty_world, save_world};

const GENERATED_FILE_HEADER: &str = r#"// -----------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by Runvy Editor.
//     Do not edit it manually.
// </auto-generated>
// -----------------------------------------------------------------------------

"#;

fn cargo_installed() -> bool {
    std::process::Command::new("cargo")
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok()
}

fn validate_project_name(name: &str) -> Result<(), ProjectError> {
    if name.trim().is_empty() {
        return Err(ProjectError::InvalidProjectName(name.into()));
    }
    let sanitized = sanitize_binary_name(name);
    if sanitized.is_empty() || sanitized == "runvy_game" {
        return Err(ProjectError::InvalidProjectName(name.into()));
    }
    Ok(())
}

fn validate_destination(destination: &Path) -> Result<(), ProjectError> {
    if destination.exists() {
        let mut entries = match destination.read_dir() {
            Ok(reader) => reader,
            Err(error) => return Err(ProjectError::Io(error)),
        };
        if entries.next().is_some() {
            return Err(ProjectError::DestinationNotEmpty(destination.to_path_buf()));
        }
    }
    Ok(())
}

pub fn create_empty_project(
    destination: &Path,
    project_name: &str,
) -> Result<ProjectPaths, ProjectError> {
    if !cargo_installed() {
        return Err(ProjectError::CargoNotInstalled);
    }
    validate_project_name(project_name)?;
    validate_destination(destination)?;

    let root_dir = destination.to_path_buf();
    let binary_name = sanitize_binary_name(project_name);

    let manifest_file_name = format!("{binary_name}.runvyproj");
    let manifest_path = root_dir.join(&manifest_file_name);

    let worlds_dir = root_dir.join("worlds");
    let assets_dir = root_dir.join("assets");
    let src_dir = root_dir.join("src");
    let proj_dir = root_dir.join(".proj");

    let startup_world_path = worlds_dir.join("main.world.ron");

    fs::create_dir_all(&root_dir)?;
    fs::create_dir_all(&worlds_dir)?;
    fs::create_dir_all(&assets_dir)?;
    fs::create_dir_all(&src_dir)?;
    fs::create_dir_all(&proj_dir)?;

    let manifest = ProjectManifest {
        name: project_name.to_string(),
        engine_version: env!("CARGO_PKG_VERSION").to_string(),
        startup_world: normalize_relative_path(Path::new("worlds").join("main.world.ron")),
        assets_dir: "assets".to_string(),
        worlds_dir: "worlds".to_string(),
        scripts_dir: "src".to_string(),
        binary_name: binary_name.clone(),
        app: ProjectAppConfig {
            window_title: project_name.to_string(),
            ..ProjectAppConfig::default()
        },
        build: ProjectBuildConfig::default(),
    };

    let project = ProjectPaths {
        manifest_path,
        root_dir: root_dir.clone(),
        manifest,
    };

    project.save_manifest()?;

    {
        let world = create_empty_world();
        let world_ref = world.borrow();
        save_world(&startup_world_path, &world_ref)?;
    }

    fs::write(root_dir.join(".gitignore"), default_gitignore())?;
    fs::write(
        root_dir.join("Cargo.toml"),
        cargo_toml_template(&binary_name),
    )?;
    fs::write(src_dir.join("main.rs"), main_rs_template())?;

    ensure_editor_bridge_files(&root_dir)?;
    ensure_release_windows_subsystem(&root_dir, true)?;

    Ok(project)
}

pub fn ensure_editor_bridge_files(project_root: &Path) -> Result<(), ProjectError> {
    let proj_dir = project_root.join(".proj");
    fs::create_dir_all(&proj_dir)?;

    ensure_project_dependencies(project_root)?;

    fs::write(
        proj_dir.join("place_objects.rs"),
        generate_place_objects_rs(project_root)?,
    )?;

    fs::write(
        proj_dir.join("runvy_object_bridge.rs"),
        object_bridge_rs_template(),
    )?;

    Ok(())
}

/// Path to the cached bridge binary in .proj/
pub fn cached_bridge_path(project_root: &Path) -> PathBuf {
    let binary_name = if cfg!(target_os = "windows") {
        "runvy_object_bridge.exe"
    } else {
        "runvy_object_bridge"
    };
    project_root.join(".proj").join(binary_name)
}

pub fn ensure_bridge_binary(project_root: &Path) -> Result<(), ProjectError> {
    let cached = cached_bridge_path(project_root);

    // If binary already exists and sources haven't changed, skip compilation
    if cached.exists() {
        let binary_modified = fs::metadata(&cached)
            .and_then(|m| m.modified())
            .unwrap_or(std::time::SystemTime::UNIX_EPOCH);

        let src_dir = project_root.join("src");
        let proj_dir = project_root.join(".proj");
        let mut latest_source = binary_modified;

        let mut check = |path: &Path| {
            if path.exists() {
                if let Ok(m) = fs::metadata(path).and_then(|m| m.modified()) {
                    if m > latest_source {
                        latest_source = m;
                    }
                }
            }
        };
        check(&src_dir.join("main.rs"));

        if let Ok(entries) = fs::read_dir(&proj_dir) {
            for entry in entries.flatten() {
                check(&entry.path());
            }
        }

        if latest_source <= binary_modified {
            return Ok(());
        }
    }

    let status = std::process::Command::new("cargo")
        .args(["build", "--bin", "runvy_object_bridge", "--quiet"])
        .current_dir(project_root)
        .status()
        .map_err(|error| ProjectError::Message(format!("failed to run cargo build for bridge: {error}")))?;

    if !status.success() {
        return Err(ProjectError::BridgeCompilationFailed(
            "cargo build --bin runvy_object_bridge failed".into(),
        ));
    }

    // Copy binary from target to .proj/
    let profile = if cfg!(debug_assertions) { "debug" } else { "release" };
    let target_binary = project_root.join("target").join(profile).join(
        if cfg!(target_os = "windows") {
            "runvy_object_bridge.exe"
        } else {
            "runvy_object_bridge"
        },
    );

    if target_binary.exists() {
        fs::copy(&target_binary, &cached)?;
    }

    Ok(())
}

pub fn ensure_release_windows_subsystem(
    project_root: &Path,
    enabled: bool,
) -> Result<(), ProjectError> {
    const ATTR: &str =
        "#![cfg_attr(all(windows, not(debug_assertions)), windows_subsystem = \"windows\")]";

    let main_rs_path = project_root.join("src").join("main.rs");

    if !main_rs_path.exists() {
        return Ok(());
    }

    let mut content = fs::read_to_string(&main_rs_path)?;
    let has_attr = content.lines().next().map(|line| line.trim()) == Some(ATTR);

    if enabled && !has_attr {
        content = format!("{ATTR}\n\n{content}");
    } else if !enabled && has_attr {
        content = content.replacen(&format!("{ATTR}\n\n"), "", 1);
        content = content.replacen(&format!("{ATTR}\n"), "", 1);
        content = content.replacen(ATTR, "", 1);
    }

    fs::write(main_rs_path, content)?;
    Ok(())
}

fn ensure_project_dependencies(project_root: &Path) -> Result<(), ProjectError> {
    let cargo_toml_path = project_root.join("Cargo.toml");

    if !cargo_toml_path.exists() {
        return Ok(());
    }

    let mut content = fs::read_to_string(&cargo_toml_path)?;
    let mut changed = false;

    if !content.contains("\nron = ") && !content.starts_with("ron = ") {
        if let Some(index) = content.find("[dependencies]") {
            let insert_at = content[index..]
                .find('\n')
                .map(|offset| index + offset + 1)
                .unwrap_or(content.len());

            content.insert_str(insert_at, "ron = \"0.8\"\n");
            changed = true;
        }
    }

    if !content.contains("name = \"runvy_object_bridge\"") {
        content.push_str(
            "\n[[bin]]\nname = \"runvy_object_bridge\"\npath = \".proj/runvy_object_bridge.rs\"\n",
        );
        changed = true;
    }

    if changed {
        fs::write(cargo_toml_path, content)?;
    }

    Ok(())
}

fn cargo_toml_template(binary_name: &str) -> String {
    let engine_root = engine_root_dir();
    let runvy_engine_path = normalize_absolute_path(engine_root.join("crates").join("runvy_engine"));

    format!(
        r#"[package]
name = "{binary_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8"
runvy_engine = {{ path = "{runvy_engine_path}" }}

[[bin]]
name = "runvy_object_bridge"
path = ".proj/runvy_object_bridge.rs"

"#
    )
}

fn main_rs_template() -> &'static str {
    r#"#![cfg_attr(all(windows, not(debug_assertions)), windows_subsystem = "windows")]

use std::sync::Arc;

use runvy_engine::{
    runvy_app::{RunvyApp, RunvyWindowConfig},
    runvy_project::{load_project, load_world_with_runtime_registry},
    Engine,
};

pub fn register_game_types(_engine: &mut Engine) {
    // Register your components, scripts, and archetypes here.
}

fn main() {
    let current_dir = std::env::current_dir()
        .expect("Failed to get current directory");

    let project = load_project(&current_dir)
        .expect("Failed to load .runvyproj manifest");

    let mut engine = Engine::new();
    register_game_types(&mut engine);

    let world = load_world_with_runtime_registry(
        project.startup_world_path(),
        engine.runtime_registry(),
    )
    .expect("Failed to load startup world");

    {
        let mut world_mut = world.borrow_mut();
        world_mut.set_runtime_registry(Arc::new(engine.runtime_registry().clone()));
    }

    let config = RunvyWindowConfig {
        title: project.manifest.app.window_title.clone(),
        width: project.manifest.app.width,
        height: project.manifest.app.height,
        fullscreen: project.manifest.app.fullscreen,
        vsync: project.manifest.app.vsync,
        show_fps_in_title: project.manifest.app.show_fps_in_title,
        window_icon: project.manifest.app.window_icon.clone(),
    };

    RunvyApp::run_with_config(world, config)
        .expect("Failed to run project");
}
"#
}

fn object_bridge_rs_template() -> String {
    format!(
        r#"{GENERATED_FILE_HEADER}#[path = "../src/main.rs"]
mod game_main;

use runvy_engine::{{
    runvy_core::registry::{{RegisteredTypeKind, RegistrationSource}},
    runvy_project::{{
        PlaceableObjectDescriptor, PlaceableObjectRecord, ProjectMetadataSnapshot,
        ProjectRegisteredTypeKind, ProjectRegisteredTypeRecord, ProjectRegistrationSource,
        WorldObjectAsset,
    }},
    Engine,
}};

fn project_metadata() -> ProjectMetadataSnapshot {{
    let mut engine = Engine::new();
    game_main::register_game_types(&mut engine);

    let registered_types = engine
        .runtime_registry()
        .types()
        .registered_types()
        .into_iter()
        .map(|metadata| ProjectRegisteredTypeRecord {{
            type_name: metadata.type_name().to_string(),
            kind: match metadata.kind() {{
                RegisteredTypeKind::Component => ProjectRegisteredTypeKind::Component,
                RegisteredTypeKind::Script => ProjectRegisteredTypeKind::Script,
            }},
            source: match metadata.source() {{
                RegistrationSource::BuiltIn => ProjectRegistrationSource::BuiltIn,
                RegistrationSource::User => ProjectRegistrationSource::User,
            }},
            editor_addable: engine
                .runtime_registry()
                .types()
                .has_object_factory(metadata.type_id()),
            default_fields: {{
                let mut object = runvy_engine::runvy_core::ocs::Object::new("Editor Preview");

                if engine
                    .runtime_registry()
                    .add_type_to_object(&mut object, metadata.type_id())
                {{
                    object
                        .with_component_by_type_id(metadata.type_id(), |component| {{
                            component.serialized_fields()
                        }})
                        .unwrap_or_default()
                }} else {{
                    Vec::new()
                }}
            }},
        }})
        .collect();

    let object_records = engine
        .runtime_registry()
        .archetypes()
        .registered_user_archetypes()
        .into_iter()
        .filter_map(|archetype| {{
            let world = engine.create_world();

            let object_id = {{
                let mut world_mut = world.borrow_mut();
                engine.spawn_def_by_name(&mut world_mut, archetype.name())?
            }};

            let object_asset = {{
                let world_ref = world.borrow();
                let object = world_ref.object(object_id)?;
                WorldObjectAsset::from_object(object)
            }};

            Some(PlaceableObjectRecord {{
                descriptor: PlaceableObjectDescriptor {{
                    id: archetype.key().as_str().to_string(),
                    name: archetype.name().to_string(),
                    category: "Object Definitions".to_string(),
                }},
                object: object_asset,
            }})
        }})
        .collect();

    ProjectMetadataSnapshot {{
        object_records,
        registered_types,
    }}
}}

fn main() {{
    let args: Vec<String> = std::env::args().collect();

    if args.len() >= 2 && args[1] == "--project-metadata" {{
        let content = ron::to_string(&project_metadata())
            .expect("Failed to serialize project metadata");
        println!("{{content}}");
        return;
    }}

    panic!("runvy_object_bridge expects --project-metadata");
}}
"#
    )
}

fn generate_place_objects_rs(_project_root: &Path) -> Result<String, ProjectError> {
    Ok(format!(
        r#"{}use runvy_engine::runvy_project::placeable_objects;

pub fn descriptors() -> Vec<runvy_engine::runvy_project::PlaceableObjectDescriptor> {{
    placeable_objects::default_records()
        .into_iter()
        .map(|r| r.descriptor)
        .collect()
}}

pub fn spawn(object_id: &str) -> Option<runvy_engine::runvy_project::WorldObjectAsset> {{
    placeable_objects::default_records()
        .into_iter()
        .find(|r| r.descriptor.id == object_id)
        .map(|r| r.object)
}}

pub fn records() -> Vec<runvy_engine::runvy_project::PlaceableObjectRecord> {{
    placeable_objects::default_records()
}}
"#,
        GENERATED_FILE_HEADER
    ))
}

fn default_gitignore() -> &'static str {
    "target/\n"
}

fn sanitize_binary_name(name: &str) -> String {
    let mut result = String::new();

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            result.push(ch.to_ascii_lowercase());
        } else if matches!(ch, ' ' | '-' | '_') && !result.ends_with('_') {
            result.push('_');
        }
    }

    let trimmed = result.trim_matches('_');

    if trimmed.is_empty() {
        "runvy_game".to_string()
    } else {
        trimmed.to_string()
    }
}

fn engine_root_dir() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("runvy_project must live in crates/runvy_project")
        .to_path_buf()
}

fn normalize_absolute_path(path: PathBuf) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn normalize_relative_path(path: PathBuf) -> String {
    path.to_string_lossy().replace('\\', "/")
}
