//! Low-level bridge between Rust and Luau.
//!
//! Defines [`ScriptType`] (a compile-time registration record for a scriptable
//! Rust type) and the `inventory`-based collection that lets any crate mark its
//! types as scriptable without creating a dependency back to `runvy_engine::scripting`.
//!
//! Also provides math conversions (`glam` <-> Luau tables) and re-exports the
//! `luau` embedding API so derive-generated code can stay decoupled from the
//! concrete `luau` crate version.
//!
//! # Type-generation model
//!
//! `runvy.luau` (read by `luau-lsp`) is generated from two layers:
//!
//! - the **engine base** (`scripts/runvy_base.luau`), which ships with the engine
//!   and contains everything marked `#[script(builtin)]` (the engine's own
//!   components, math types, `KeyCode`/`ScriptInput`, `ScriptContext`, ...).
//!   It is regenerated by the `gen-runvy-base` binary and committed to the repo;
//! - the **project layer**: user components / aux types / functions registered in
//!   the *running binary*, which are spliced into the base at the `-- @@runvy:*@@`
//!   markers by [`write_luau_types`].
//!
//! This keeps a single source of truth (the Rust definitions) while making sure
//! no file needs to be hand-edited inside a user project: the engine ships the
//! built-in types, and user types are appended automatically from `inventory`.

use runvy_ecs::{Entity, World};

// Re-export the embedding API so generated code only needs `runvy_script_api`.
pub use inventory;
pub use inventory::{collect, iter, submit};
pub use luau;

/// A scriptable Rust type: its Luau type definition string plus the functions
/// that project it into / out of a Luau table for a given `Entity`.
///
/// `builtin` marks engine-owned types: they are part of the committed
/// `runvy_base.luau` and are *not* re-emitted when a user project generates its
/// own `runvy.luau`.
pub struct ScriptType {
    pub name: &'static str,
    pub type_def: &'static str,
    pub to_luau: for<'lua> fn(luau::LuaRef<'lua>, &World, Entity) -> Option<luau::Table<'lua>>,
    pub from_luau: for<'lua> fn(luau::LuaRef<'lua>, luau::Value<'lua>, &mut World, Entity),
    /// Insert-or-create this component from a Luau table (`ctx:AddComponent`).
    pub add: for<'lua> fn(luau::LuaRef<'lua>, luau::Value<'lua>, &mut World, Entity),
    /// Remove this component from an entity (`ctx:RemoveComponent`).
    pub remove: fn(&mut World, Entity),
    /// Whether this type ships with the engine (`#[script(builtin)]`).
    pub builtin: bool,
}

impl Clone for ScriptType {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for ScriptType {}

inventory::collect!(ScriptType);

/// A non-component Lua type referenced by scriptable fields (tagged unions such
/// as `Collider2DShape`, string unions such as `ProjectionType`, flag structs
/// such as `ScreenEffectFlags`). Registered next to the Rust type it describes;
/// merely contributes its `type_def` to the generated `runvy.luau`.
pub struct ScriptAuxType {
    pub name: &'static str,
    /// Full `export type Name = ...` definition, emitted verbatim.
    pub type_def: &'static str,
    /// Whether this type ships with the engine (`#[script(builtin)]`).
    pub builtin: bool,
}

impl Clone for ScriptAuxType {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for ScriptAuxType {}

inventory::collect!(ScriptAuxType);

/// Math type conversions between `glam` and Luau tables. These are free
/// functions (not trait impls) so we avoid the orphan rule — the derive macro
/// emits calls to them for `Vec2`/`Vec3`/`Vec4`/`Quat` fields.
pub mod math {
    use glam::{Quat, Vec2, Vec3, Vec4};
    use luau::{Error, LuaRef, Result, Table};

    pub fn vec2_to_luau(lua: LuaRef<'_>, v: Vec2) -> Result<Table<'_>> {
        let t = lua.create_table()?;
        t.set("x", v.x as f64)?;
        t.set("y", v.y as f64)?;
        Ok(t)
    }

    pub fn vec2_from_luau(t: &Table) -> Vec2 {
        Vec2::new(
            t.get::<f64>("x").unwrap_or(0.0) as f32,
            t.get::<f64>("y").unwrap_or(0.0) as f32,
        )
    }

    pub fn vec3_to_luau(lua: LuaRef<'_>, v: Vec3) -> Result<Table<'_>> {
        let t = lua.create_table()?;
        t.set("x", v.x as f64)?;
        t.set("y", v.y as f64)?;
        t.set("z", v.z as f64)?;
        Ok(t)
    }

    pub fn vec3_from_luau(t: &Table) -> Vec3 {
        Vec3::new(
            t.get::<f64>("x").unwrap_or(0.0) as f32,
            t.get::<f64>("y").unwrap_or(0.0) as f32,
            t.get::<f64>("z").unwrap_or(0.0) as f32,
        )
    }

    pub fn vec4_to_luau(lua: LuaRef<'_>, v: Vec4) -> Result<Table<'_>> {
        let t = lua.create_table()?;
        t.set("x", v.x as f64)?;
        t.set("y", v.y as f64)?;
        t.set("z", v.z as f64)?;
        t.set("w", v.w as f64)?;
        Ok(t)
    }

    pub fn vec4_from_luau(t: &Table) -> Vec4 {
        Vec4::new(
            t.get::<f64>("x").unwrap_or(0.0) as f32,
            t.get::<f64>("y").unwrap_or(0.0) as f32,
            t.get::<f64>("z").unwrap_or(0.0) as f32,
            t.get::<f64>("w").unwrap_or(0.0) as f32,
        )
    }

    pub fn quat_to_luau(lua: LuaRef<'_>, q: Quat) -> Result<Table<'_>> {
        vec4_to_luau(lua, Vec4::new(q.x, q.y, q.z, q.w))
    }

    pub fn quat_from_luau(t: &Table) -> Quat {
        let v = vec4_from_luau(t);
        Quat::from_xyzw(v.x, v.y, v.z, v.w)
    }

    /// Used by error-free fallbacks when a math field is missing/garbage.
    pub fn err_type(name: &str) -> Error {
        Error::runtime(format!("scriptable: expected table for {name}"))
    }
}

// ---------------------------------------------------------------------------
// Type generation
// ---------------------------------------------------------------------------

/// Marker substituted by the project layer (user types) during generation.
/// These lines live in `runvy_base.luau` and are replaced by [`render_runvy_project`].
const MARKER_TYPES: &str = "-- @@runvy:types@@\n";
const MARKER_MARKERS: &str = "-- @@runvy:markers@@\n";
const MARKER_RETURN: &str = "-- @@runvy:return@@\n";

/// The engine's committed base file, embedded so project generation never needs
/// to locate the engine on disk.
const RUN_BASE: &str = include_str!("../scripts/runvy_base.luau");

/// The generated sections for one layer (`builtin == true` for the engine base,
/// `false` for a user project).
struct Sections {
    /// `export type` definitions (aux types first, then components), sorted by
    /// name so generation is deterministic.
    types: String,
    /// `local Name: Name = {} :: Name;` class markers, sorted.
    markers: String,
    /// `     Name = Name,` class fields + `name = function(...) ... end,` stubs.
    return_fields: String,
}

fn collect_sections(builtin: bool) -> Sections {
    let mut aux: Vec<(String, String)> = iter::<ScriptAuxType>()
        .filter(|a| a.builtin == builtin)
        .map(|a| (a.name.to_string(), a.type_def.to_string()))
        .collect();
    let mut comps: Vec<(String, String)> = iter::<ScriptType>()
        .filter(|t| t.builtin == builtin)
        .map(|t| (t.name.to_string(), t.type_def.to_string()))
        .collect();
    aux.sort_by(|a, b| a.0.cmp(&b.0));
    comps.sort_by(|a, b| a.0.cmp(&b.0));

    let mut types = String::new();
    for (_, def) in aux.iter().chain(comps.iter()) {
        types.push_str(def);
        types.push('\n');
    }
    if !types.is_empty() {
        types.push('\n');
    }

    let mut markers = String::new();
    for (name, _) in &comps {
        markers.push_str(&format!("local {name}: {name} = {{}} :: {name};\n"));
    }

    let mut return_fields = String::new();
    for (name, _) in &comps {
        return_fields.push_str(&format!("    {name} = {name},\n"));
    }

    Sections {
        types,
        markers,
        return_fields,
    }
}

/// Render the engine's immutable base module: every `#[script(builtin)]` type
/// plus the `-- @@runvy:*@@` markers where a user project's own types get spliced in.
pub fn render_runvy_base() -> String {
    let builtin = collect_sections(true);

    let mut s = String::new();
    s.push_str(&header());
    s.push_str(&math_types());
    s.push_str(&format!("export type KeyCode = {}\n\n", keycode_union()));
    s.push_str(&script_input());
    s.push_str("export type ScriptEvent = { name: string, x: number, y: number }\n\n");

    s.push_str(&builtin.types);
    s.push_str(MARKER_TYPES);
    s.push_str(&builtin.markers);
    s.push_str(MARKER_MARKERS);

    s.push_str(
        "export type ScriptContext = {\n    entity: number,\n    dt: number,\n    input: ScriptInput,\n    components: { [string]: any },\n    events: { ScriptEvent },\n    events_in: { ScriptEvent },\n",
    );
    s.push_str(
        "    GetComponent: <T>(self: ScriptContext, component: T) -> T,\n    HasComponent: <T>(self: ScriptContext, component: T) -> boolean,\n    AddComponent: <T>(self: ScriptContext, component: T, value: any) -> (),\n    RemoveComponent: <T>(self: ScriptContext, component: T) -> (),\n    Spawn: (self: ScriptContext, path: string) -> (),\n    Destroy: (self: ScriptContext, entity: number) -> (),\n}\n\n",
    );

    s.push_str("return {\n");
    s.push_str(&builtin.return_fields);
    s.push_str(MARKER_RETURN);
    s.push_str("    vec2 = function(x: number, y: number): Vec2 return { x = x, y = y } end,\n");
    s.push_str("    vec3 = function(x: number, y: number, z: number): Vec3 return { x = x, y = y, z = z } end,\n");
    s.push_str("    vec4 = function(x: number, y: number, z: number, w: number): Vec4 return { x = x, y = y, z = z, w = w } end,\n");
    s.push_str("    quat = function(x: number, y: number, z: number, w: number): Quat return { x = x, y = y, z = z, w = w } end,\n");
    s.push_str("    normalize2 = function(v: Vec2): Vec2 return v end,\n");
    s.push_str("    normalize3 = function(v: Vec3): Vec3 return v end,\n");
    s.push_str("    length2 = function(v: Vec2): number return 0 end,\n");
    s.push_str("    length3 = function(v: Vec3): number return 0 end,\n");
    s.push_str("    pi = 3.141592653589793,\n");
    s.push_str("    cos = function(x: number): number return 0 end,\n");
    s.push_str("    sin = function(x: number): number return 0 end,\n");
    s.push_str("    tan = function(x: number): number return 0 end,\n");
    s.push_str("    atan2 = function(y: number, x: number): number return 0 end,\n");
    s.push_str("    sqrt = function(x: number): number return 0 end,\n");
    s.push_str("    abs = function(x: number): number return 0 end,\n");
    s.push_str("    floor = function(x: number): number return 0 end,\n");
    s.push_str("    ceil = function(x: number): number return 0 end,\n");
    s.push_str("    round = function(x: number): number return 0 end,\n");
    s.push_str("    sign = function(x: number): number return 0 end,\n");
    s.push_str("    pow = function(x: number, y: number): number return 0 end,\n");
    s.push_str("    max = function(a: number, b: number): number return 0 end,\n");
    s.push_str("    min = function(a: number, b: number): number return 0 end,\n");
    s.push_str("    clamp = function(x: number, lo: number, hi: number): number return 0 end,\n");
    s.push_str("    rad = function(x: number): number return 0 end,\n");
    s.push_str("    deg = function(x: number): number return 0 end,\n");
    s.push_str("}\n");
    s
}

/// Render a *user project's* `runvy.luau`: the engine base spliced together with
/// every non-builtin type / function registered in this binary (via `inventory`).
pub fn render_runvy_project() -> String {
    let user = collect_sections(false);
    RUN_BASE
        .replace(MARKER_TYPES, &user.types)
        .replace(MARKER_MARKERS, &user.markers)
        .replace(MARKER_RETURN, &user.return_fields)
}

/// Regenerate `scripts/runvy_base.luau` inside the engine. Run the
/// `gen-runvy-base` binary (linked against the engine) to refresh it after
/// changing a `#[script(builtin)]` component.
pub fn write_runvy_base(path: &std::path::Path) {
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, render_runvy_base());
}

/// Regenerates the Luau type-definition module (`runvy.luau`) that `luau-lsp`
/// reads for autocomplete / type checking. Call this from your game's startup
/// (once) with the output path, e.g.
/// `write_luau_types(Path::new(".runvy/runvy.luau"))`.
///
/// The emitted file is the engine's committed base (`scripts/runvy_base.luau`)
/// plus everything your binary registers as scriptable via
/// `#[derive(Scriptable)]` / aux type registrations.
pub fn write_luau_types(path: &std::path::Path) {
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, render_runvy_project());
}

fn header() -> String {
    let mut s = String::new();
    s.push_str("-- THIS FILE IS GENERATED. DO NOT EDIT BY HAND.\n");
    s.push_str("-- The engine layer (`runvy_base.luau`, built-in types) is regenerated by the\n");
    s.push_str(
        "-- `gen-runvy-base` binary; your project's own types are appended from `inventory`.\n",
    );
    s.push_str("-- Read by `luau-lsp` for type checking and autocomplete.\n\n");
    s
}

fn math_types() -> String {
    "export type Vec3 = { x: number, y: number, z: number }\nexport type Vec4 = { x: number, y: number, z: number, w: number }\nexport type Vec2 = { x: number, y: number }\nexport type Quat = { x: number, y: number, z: number, w: number }\n\n".to_string()
}

fn script_input() -> String {
    let kc = keycode_names();
    let mut s = String::from("export type ScriptInput = {\n");
    for k in kc {
        s.push_str(&format!("    {k}: boolean,\n"));
    }
    s.push_str("    keys_just_pressed: { [string]: boolean },\n");
    s.push_str("    mouse_buttons_pressed: { [string]: boolean },\n");
    s.push_str("    mouse_buttons_just_pressed: { [string]: boolean },\n");
    s.push_str("    mouse_position: { x: number, y: number },\n");
    s.push_str("    mouse_delta: { x: number, y: number },\n");
    s.push_str("    mouse_wheel_delta: number,\n");
    s.push_str("    is_key_pressed: (self: ScriptInput, key: KeyCode) -> boolean,\n");
    s.push_str("    is_key_just_pressed: (self: ScriptInput, key: KeyCode) -> boolean,\n");
    s.push_str("    is_mouse_pressed: (self: ScriptInput, button: string) -> boolean,\n");
    s.push_str("    is_mouse_just_pressed: (self: ScriptInput, button: string) -> boolean,\n");
    s.push_str("    get_mouse_position: (self: ScriptInput) -> { x: number, y: number },\n");
    s.push_str("}\n\n");
    s
}

fn keycode_union() -> String {
    keycode_names()
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn keycode_names() -> &'static [&'static str] {
    &[
        "KeyA",
        "KeyB",
        "KeyC",
        "KeyD",
        "KeyE",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyI",
        "KeyJ",
        "KeyK",
        "KeyL",
        "KeyM",
        "KeyN",
        "KeyO",
        "KeyP",
        "KeyQ",
        "KeyR",
        "KeyS",
        "KeyT",
        "KeyU",
        "KeyV",
        "KeyW",
        "KeyX",
        "KeyY",
        "KeyZ",
        "Digit0",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "ArrowUp",
        "ArrowDown",
        "ArrowLeft",
        "ArrowRight",
        "Space",
        "Enter",
        "Escape",
        "Tab",
        "Backspace",
        "Delete",
        "Home",
        "End",
        "PageUp",
        "PageDown",
        "Insert",
        "ShiftLeft",
        "ShiftRight",
        "ControlLeft",
        "ControlRight",
        "AltLeft",
        "AltRight",
        "Meta",
        "SuperLeft",
        "SuperRight",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "Backquote",
        "Minus",
        "Equal",
        "BracketLeft",
        "BracketRight",
        "Backslash",
        "Semicolon",
        "Quote",
        "Comma",
        "Period",
        "Slash",
        "Numpad0",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadAdd",
        "NumpadSubtract",
        "NumpadMultiply",
        "NumpadDivide",
        "NumpadDecimal",
        "NumpadEnter",
    ]
}
