[package]
name = "runvy_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
egui = "0.35"
egui-wgpu = "0.35"
egui-winit = "0.35"
egui_extras = "0.35"
egui_dock = "0.20"
winit.workspace = true
wgpu.workspace = true
pollster.workspace = true

[build-dependencies]
image = { version = "0.25", features = ["png", "ico"] }
ico = "0.4"
winres = "0.1"