[package]
name = "runvy_core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
runvy_asset = { path = "../runvy_asset" }
runvy_ecs = { path = "../runvy_ecs" }
runvy_macros = { path = "../runvy_macros" }
runvy_script_api = { path = "../runvy_script_api" }
runvy_render = { path = "../runvy_render" }
runvy_render_api = { path = "../runvy_render_api" }

glam.workspace = true
winit.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
bytemuck = { version = "1.25.0", features = ["derive"] }
rodio = "0.22"
ron = "0.12.0"
inventory = "0.3"
